apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: assignment3
type: Opaque
data:
  root_password: cm9vdHBhc3M=      # rootpass
  db_name: YXNzaWdubWVudDNkYg==   # assignment3db
  db_user: Zmxhc2tfdXNlcg==        # flask_user
  db_password: Zmxhc2twYXNz        # flaskpass
